name: Mark stale issues

on:
  workflow_dispatch:
  schedule:
    - cron: "30 1 * * *"

permissions:
  issues: write

jobs:
  stale:
    if: github.repository == 'github/codeql'

    runs-on: ubuntu-latest

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@5c7944e73c4c2a096b17a9cb74d65b6c2bbafbde # v2.9.1
      with:
        egress-policy: audit

    - uses: actions/stale@28ca1036281a5e5922ead5184a1bbf96e5fc984e # v9.0.0
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue is stale because it has been open 14 days with no activity. Comment or remove the `Stale` label in order to avoid having this issue closed in 7 days.'
        close-issue-message: 'This issue was closed because it has been inactive for 7 days.'
        days-before-stale: 14
        days-before-close: 7
        only-labels: awaiting-response

        # do not mark PRs as stale
        days-before-pr-stale: -1
        days-before-pr-close: -1

        # Uncomment for dry-run
        # debug-only: true
        # operations-per-run: 1000
