name: Regenerate framework models

on:
  workflow_dispatch:
  schedule:
    - cron: "30 2 * * *"
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/mad_regenerate-models.yml"
      - ".github/actions/fetch-codeql/action.yml"

permissions:
  contents: read

jobs:
  regenerate-models:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # placeholder required for each axis, excluded below, replaced by the actual combinations (see include)
        slug: ["placeholder"]
        ref: ["placeholder"]
        include:
          - slug: "apache/commons-io"
            ref: "13258ce2d07aa0e764bbaa8020af4dcd3a02a620"
        exclude:
          - slug: "placeholder"
            ref: "placeholder"
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@5c7944e73c4c2a096b17a9cb74d65b6c2bbafbde # v2.9.1
        with:
          egress-policy: audit

      - name: Clone self (github/codeql)
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Setup CodeQL binaries
        uses: ./.github/actions/fetch-codeql
      - name: Clone repositories
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          path: repos/${{ matrix.ref }}
          ref: ${{ matrix.ref }}
          repository: ${{ matrix.slug }}
      - name: Build database
        env:
          SLUG: ${{ matrix.slug }}
          REF: ${{ matrix.ref }}
        run: |
          mkdir dbs
          cd repos/${REF}
          SHORTNAME=${SLUG//[^a-zA-Z0-9_]/}
          codeql database create --language=java ../../dbs/${SHORTNAME}
      - name: Regenerate models in-place
        env:
          SLUG: ${{ matrix.slug }}
        run: |
          SHORTNAME=${SLUG//[^a-zA-Z0-9_]/}
          java/ql/src/utils/modelgenerator/RegenerateModels.py "${SLUG}" dbs/${SHORTNAME}
      - name: Stage changes
        run: |
          find java -name "*.model.yml" -print0 | xargs -0 git add
          git status
          git diff --cached > models.patch
      - uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
        with:
          name: patch
          path: models.patch
          retention-days: 7
