name: Check synchronized files

on:
  push:
    branches:
      - main
      - 'rc/*'
  pull_request:
    branches:
      - main
      - 'rc/*'

permissions:
  contents: read

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@5c7944e73c4c2a096b17a9cb74d65b6c2bbafbde # v2.9.1
        with:
          egress-policy: audit

      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Check synchronized files
        run: python config/sync-files.py
      - name: Check dbscheme fragments
        run: python config/sync-dbscheme-fragments.py

