name: Test tree-sitter-extractor

on:
  push:
    paths:
      - "shared/tree-sitter-extractor/**"
      - .github/workflows/tree-sitter-extractor-test.yml
    branches:
      - main
      - "rc/*"
  pull_request:
    paths:
      - "shared/tree-sitter-extractor/**"
      - .github/workflows/tree-sitter-extractor-test.yml
    branches:
      - main
      - "rc/*"

env:
  CARGO_TERM_COLOR: always

defaults:
  run:
    working-directory: shared/tree-sitter-extractor

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@5c7944e73c4c2a096b17a9cb74d65b6c2bbafbde # v2.9.1
        with:
          egress-policy: audit

      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Check formatting
        run: cargo fmt --all -- --check
      - name: Run tests
        run: cargo test --verbose
  fmt:
    runs-on: ubuntu-latest  
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@5c7944e73c4c2a096b17a9cb74d65b6c2bbafbde # v2.9.1
        with:
          egress-policy: audit

      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Check formatting
        run: cargo fmt --check
  clippy:
    runs-on: ubuntu-latest  
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@5c7944e73c4c2a096b17a9cb74d65b6c2bbafbde # v2.9.1
        with:
          egress-policy: audit

      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Run clippy
        run: cargo clippy -- --no-deps -D warnings -A clippy::new_without_default -A clippy::too_many_arguments
