name: Validate change notes

on:
  push:
    paths:
      - "*/ql/*/change-notes/**/*"
      - ".github/workflows/validate-change-notes.yml"
      - ".github/actions/fetch-codeql/action.yml"
    branches:
      - main
      - "rc/*"
  pull_request:
    paths:
      - "*/ql/*/change-notes/**/*"
      - ".github/workflows/validate-change-notes.yml"
      - ".github/actions/fetch-codeql/action.yml"

permissions:
  contents: read

jobs:
  check-change-note:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@5c7944e73c4c2a096b17a9cb74d65b6c2bbafbde # v2.9.1
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Setup CodeQL
        uses: ./.github/actions/fetch-codeql

      - name: Fail if there are any errors with existing change notes

        run: |
          codeql pack release --groups cpp,csharp,java,javascript,python,ruby,-examples,-test,-experimental
